
name: C Program CI

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for compilation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install GCC
        run: sudo apt-get install -y gcc

      - name: Compile C Program
        run: gcc -o gitfirstcode gitfirstcode.c

      - name: Run the Program
        run: ./gitfirstcode