name: My First Workflow  # (Optional) Name of the workflow

on: 
  push:  # Trigger when code is pushed
    branches: 
      - main  # Runs only on the 'main' branch
  pull_request:  # Trigger when a PR is opened

jobs:
  build:  # Job name
    runs-on: ubuntu-latest  # Defines the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Pulls the repository code

      - name: Run a sample script
        run: echo "Hello, GitHub Actions!"  # Executes a command
